### ISSUE TITLE
Results Module: Quality of Care is going off the screen slightly

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#16]
Feedback from gtsmith@psi.org : Quality of Care is going off the screen slightly

 [Link to buddybuild feedback from build 4](https://api.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5720123e871f1e0100ab9861&bnum=4)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5716f530fe9bb40100ff4a06/57a319d1-97d4-4d01-9db4-3dfaf44e9739.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>82% Unplugged</td></tr><tr><td>Memory free</td><td>277 MB / 1319 MB</td></tr></table>

**Comment by smburnett** [comment]
Fixed.
