### ISSUE TITLE
sburnett@path.org on build #6: Supervisor telephone  not letting me type in the box

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#19]
Feedback from sburnett@path.org : Supervisor telephone  not letting me type in the box

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=573a0c6c43dd7101009e5cdd&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/0cd01936-97db-4363-bffb-1a2f50f90ecd.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>92% Unplugged</td></tr><tr><td>Memory free</td><td>268 MB / 1319 MB</td></tr></table>

**Comment by gtrsmith** [comment]
Ignacio, dont worry about this - this is the Malawi assessment and i am not having that issue. this is a configuration issue unless there is something i am unaware of you are addressing
