### ISSUE TITLE
Lab Observation Tab: IQA/EQA Table - Text Cut-off

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#20]
Feedback from sburnett@path.org : Text cut off page

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=573a18bdaf1151010088b1a2&bnum=6)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/083a5712-4140-4a4f-8506-9f00be6cea19.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>85% Unplugged</td></tr><tr><td>Memory free</td><td>449 MB / 1319 MB</td></tr></table>

**Comment by smburnett** [comment]
This has been solved.
