### ISSUE TITLE
sburnett@path.org on build #6: Do we need a drop down here still? Will the composite scores…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#23]
Feedback from sburnett@path.org : Do we need a drop down here still? Will the composite scores go in this dropdown?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/0424703d-9fbc-4412-b89d-9ae5f6c3f75f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>21% Unplugged</td></tr><tr><td>Memory free</td><td>132 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5743c2684928b801001179ea&bnum=6)

**Comment by gtrsmith** [comment]
same issues as #34
