### ISSUE TITLE
Crash: Exit survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#24]
Server: https://eds-ke-dev.baosystems.com
EDS version: 2.0.0
User: KEtester
Program: Gen OTSS

Was in General OTSS program. Tried to exist assessment. After prompt 'Are you sure you want to exit', I clicked 'Yes'. Application went back to landing page, froze and shut down. I will try to replicate problem.

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5743c357c6d9200100845a10&bnum=6)

**Comment by gtrsmith** [comment]
Hey Ignacio, we will try to replicate this crash for you. For now, we are reporting.

**Comment by gtrsmith** [comment]
duplicate with #35
