### ISSUE TITLE
General OTSS Tab: Hangs (resolved?)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#27]
The General OTSS tab sometimes stays blank after opening and never loads. I waited for over a minute for this to load and it never it. This doesn't happen every time - just sometimes. I will try to recreate it. 

Hung again at 15:43 on my tablet, 8:41 am DC time. This was the first time I opened this module. 

When I refreshed metadata for a second time, this seemed to fix itself.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/608adf25-6a48-4ce3-935d-b812291f0837.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>1280</td></tr><tr><td>Screen size</td><td>1280px by 800px</td></tr><tr><td>Battery</td><td>26% Unplugged</td></tr><tr><td>Memory free</td><td>289 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5744a44f1135c801009760e1&bnum=6)

**Comment by gtrsmith** [comment]
Again, I adjusted the configuration. @smburnett we should test to see if this is still an issue
