### ISSUE TITLE
Survey selection page: Headers repeat on this page - Same as Issue #14?

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#28]
Sometimes when filling out the survey selection the headers will repeat themselves - as in the picture below. 

This happened once (16:08 on tablet 9:06am DC time) after I tried to open a module that already had an unsent one for that health facility. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/6abc63e4-cc9e-4cda-9518-ef8d4c5e1d79.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>79% Unplugged</td></tr><tr><td>Memory free</td><td>325 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5745de909ed8d40100861c24&bnum=6)

**Comment by gtrsmith** [comment]
This is the same issue as issue 14. I am closing the ticket and marking as duplicate
