### ISSUE TITLE
Survey Selection Page: Modify Headers

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#29]
The headers on the survey selection page should be modified as follows: 

Country :  I'm not sure we need this one, as it just has OTSS as an option? If we need to keep it I would call it Survey
County: Country
Health Facility: County
OTSS: Sub-County
Subcounty: Health Facility
Survey: Module

So in summary the order should be as follows: 
Survey
Country
County
Sub-County
Health Facility
Module

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/aefb2f51-2c2f-4035-9af0-aa9a00c7793f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>48% Charging</td></tr><tr><td>Memory free</td><td>252 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5746f1986b662b01009b604c&bnum=6)

**Comment by ifoche** [comment]
@gtrsmith, @josemp10  this is a content issue, can you take care of it (I think that it's just rename the OU levels)?

**Comment by gtrsmith** [comment]
Yes, I can try to take care of it.
