### ISSUE TITLE
Crash: Results Page (resolved?)

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#35]
Time: 16:23 on tablet, 9:21 am DC

I submitted the General OTSS observation it went down to the "Sent Assessment" section. I clicked on it and when it didn't respond, I clicked on it again. Then it shut down. 

After this i tried sending and opening another module and I couldn't open that one either. None of the Results modules will open.

**Comment by gtrsmith** [comment]
I have updated the configuration and am not having this issue. @smburnett can we test again and see if issue persists?
