### ISSUE TITLE
Crash: Adherence tab (resolved?)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#37]
I started filled in the adherence test results and it shut down.
I tried reopening 2 more times and every time I could enter a few more fields, then it would just down. 

Time: 16:30 on tablet, 9:29 am DC time. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/04463135-0c55-487f-8fa8-ddcb8d769683.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>60% Charging</td></tr><tr><td>Memory free</td><td>381 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5746f9e010afc20100909eec&bnum=6)

**Comment by gtrsmith** [comment]
I have since updated the configuration and I have not experienced this issue. I was able to enter data into every field, exit the assessment and go into feedback without problems. 

@smburnett , can you please try to replicate this issue and see if it is resolved with the updated configuration?

**Comment by smburnett** [comment]
I just recreated this and it didn't crash.

**Comment by gtrsmith** [comment]
ok - I will keep in backlog for now in case this happens again. If not we will mark as completed
