### ISSUE TITLE
Adherence Tab: Overwrites previously sent assessment?

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#38]
I had one submitted adherence module for Test HF 01. I then submitted a second adherence module for that same facility. After submitted the second adherence module there was still only one adherence module showing up under the Sent Assessments. Did the second module overwrite the first? Or did the second module not go through? 

I tried to investigate this myself but the results module won't open at all.

**Comment by gtrsmith** [comment]
Duplicate with #50
