### ISSUE TITLE
Clinical Observation Tab: Modules Hangs - No Form showing up.

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#39]
In the Clinical Observation tab no content is showing up for any of the observation tab groups. 

When I refreshed the metadata for the 3rd time this morning it did show up. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/d32e7249-9dce-48bb-b893-89e48c59e9e1.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>63% Charging</td></tr><tr><td>Memory free</td><td>388 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5746fc47bb8e3c0100ec5db9&bnum=6)

**Comment by gtrsmith** [comment]
This is due to an error in the configuration. I have fixed config error.
