### ISSUE TITLE
sburnett@path.org on build #6: Module missing

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#40]
Feedback from sburnett@path.org : Module missing

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/852000de-6778-4318-9989-bb66cd985563.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>64% Charging</td></tr><tr><td>Memory free</td><td>392 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=5746fcfa58ced701001669d0&bnum=6)

**Comment by gtrsmith** [comment]
This seems to happen when there is an issue elsewhere in one of the other programs (or other program stage sections) assigned to the user. So this might be a configuration issue but its still not good.
