### ISSUE TITLE
Survey Selection: Hierarchy levels do not reflect DHIS

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#43]
Hierarchy levels in the survey selection page do not reflect DHIS hierarchy levels. See screenshots below compared with the hierarchy levels in DHIS

![image](https://cloud.githubusercontent.com/assets/14224713/15584255/0160fe1c-2337-11e6-8cee-cd8b32ebf4ad.png)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/ff2e0464-8c1c-41a8-b4f9-08b85b2ad42d.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>21% Unplugged</td></tr><tr><td>Memory free</td><td>371 MB / 1347 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=57473518595c8d01001b03eb&bnum=6)

**Comment by ifoche** [comment]
@gtrsmith the solution to this bug is going to take a little bit longer. The problem is not in the App itself, but in the DHIS2 Android SDK (please see the image of the DB exactly how it's being delivered to the App by the SDK). 

![oulevels](https://cloud.githubusercontent.com/assets/10931645/15733550/2b141de8-2887-11e6-84bb-1b2592dc45bc.png)

**Comment by smburnett** [comment]
This seems to be fixed - except that now in the survey category OTSS is showing up and if you select it it shuts down EDS. 
![screenshot_2016-06-03-16-02-27 1](https://cloud.githubusercontent.com/assets/18399454/15779420/2d77cc22-296a-11e6-9321-b6e22b35b113.png)

**Comment by smburnett** [comment]
In version 10 this seems to be a problem again as they are no longer matching up. See the photo below. 

![hierarchy](https://cloud.githubusercontent.com/assets/18399454/15816245/9b5f8456-2bda-11e6-8c05-f8af53c43c75.png)

**Comment by ifoche** [comment]
@smburnett did you removed the previously installed app or did you installed on top of it? Because OU hierarchy is built during the metadata pull, and it seems to be like you were using the old DB. It's working for me

![create_survey](https://cloud.githubusercontent.com/assets/10931645/15817470/68fff218-2bd8-11e6-817b-a8da30e85c00.png)

**Comment by smburnett** [comment]
We're checking this onenow  - this could be a case of not uninstalling and reinstalling.
