### ISSUE TITLE
sburnett@path.org on build #6: Naming is not consistent

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#45]
Right now some items just say "ACT Prescribed?" while others say "Microscopy Negative 4 - ACT Prescribed?". 
I would prefer if we could have it as detailed as possible for all - i.e. 
Microscopy Negative 4 - ACT Prescribed 

Also, the scoring is wrong. If you are Microscopy Negative not prescribing an ACT should be correct treatment - not a fail. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/e5789144-a1a7-45d2-ac54-abfbac500106.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>289 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=57473b433278060100a52e99&bnum=6)

**Comment by gtrsmith** [comment]
@ifoche NOTE: This is assigned to GRAHAM!

**Comment by gtrsmith** [comment]
Both issues should now be fixed
