### ISSUE TITLE
Crash: Clinical Observation Results (resolved?)

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#48]
The application crashed when I tried to open the clinical observation results. 
It crashed and then showed the settings page. 

When I went back in after the crash, it opened, then crashed again. 

After this, I tried opening a new Clinical Obs module and it crashed. but after the initial crash I was able to re-open the new one and create another new one without a crash. 

I could not replicate this crash.

**Comment by gtrsmith** [comment]
This might have been due to the issue I just addressed in the clinical observation tab. There were scored hidden questions assigned to the wrong tabs. @smburnett let us know if this happens again now i have resolved that configuration issue.

**Comment by gtrsmith** [comment]
I am going to keep this in the backlog until we are able to see it again. I fixed some configuration issues that may have resolved this.
