### ISSUE TITLE
Custom form display: Blank when selecting 'show num/den'

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#49]
I clicked "Show Nums/Dems" in the setting and it made the adherence tab show up completely blank. 
I exited out, turned off the "Show Nums/Dems" setting and then re-entered the Adherence tab. It's still showing up blank now even though the setting is turned off. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5733b7f5847d970100709336/b7f2d8e2-0804-41cb-b938-e9de7ba3956f.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>6</td></tr><tr><td>Device type</td><td>SM-T217S</td></tr><tr><td>Screen size</td><td>600</td></tr><tr><td>Screen size</td><td>600px by 1024px</td></tr><tr><td>Battery</td><td>1% Unplugged</td></tr><tr><td>Memory free</td><td>350 MB / 1347 MB</td></tr></table>

 [Link to buddybuild feedback from build 6](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=57475bb288e5970100fc3a2e&bnum=6)

**Comment by smburnett** [comment]
this is fixed.
