### ISSUE TITLE
Crash: Start new assessment when unable to find 'last' assessment

### ISSUE THREAD

**Issue by gtrsmith** [EyeSeeTea/EDSApp#5]
Application crashes consistently when unable to find the 'last' assessment. See video here (https://drive.google.com/open?id=0BwFVG9gNmqDyb1hPTU81VjdfMG8)

The 'sent' assessments field on my landing page has the following assessments for org unit 'MWI outlet 1 test 2': 
- Clinical Observation 
- Laboratory Observation

When I start a new assessment for this org unit, the app crashes for any survey that is not Clinical Observation or Laboratory Observation.

**Comment by ifoche** [comment]
Closing the issue as this is not valid anymore
