### ISSUE TITLE
Add Read Only Functionality for Complete Assessments

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#51]
We will need an option to "View/Read" the full results for complete assessments, in addition to the results module. The "View/Read" should be the same as what the sent assessments review was like in E1.

**Comment by smburnett** [comment]
Seems to work - but crashes with any assessments sent before June 6th, which would be expected.

**Comment by ifoche** [comment]
@smburnett did you try to uninstall the app and install it from zero? It's working for me with surveys from any date

**Comment by smburnett** [comment]
i did uninstall and reinstall from 0.

**Comment by ifoche** [comment]
ok, can you provide me with the user/server/pass (in separate mail) to let me test it and guess what's happening? Thanks!

**Comment by smburnett** [comment]
sent!

**Comment by ifoche** [comment]
Hi again,

this screenshot comes from a fresh install and pull using the user you've just provided to me. This is a long press on a survey sent the 24 May 2016 for the OU Test HF 01, program 4. RDT Observation. And its working.

![read-only-survey](https://cloud.githubusercontent.com/assets/10931645/15818333/1efdddc4-2bdd-11e6-807a-f5aed1dce467.png)

Are you sure you're properly uninstalling the app? Some devices/android versions need you to manually go to settings -> apps, then click on the app and then uninstall, to completely remove the app. Maybe you're trying to do it from the android menu (by dragging and dropping into "remove"). May that be the case?

**Comment by smburnett** [comment]
My tablet has "Uninstall" instead of "Remove" - so that's what I did. I'll try uninstalling and reinstalling again.

**Comment by ifoche** [comment]
Ok thanks.

**Comment by smburnett** [comment]
Ok I was finally able to get a good enough internet connection to reinstall. The same thing is still happening - older submitted forms are still shutting down in EDS. I tried following the exact instructions above for uninstalling and reinstalling the application. 

Sometimes the forms will show up but then when I try to scroll down it stops functioning - even when I try scrolling down very slowly.

**Comment by ifoche** [comment]
I confirm that I have just replicated the bug. It is related to some elements that by coincidence were not present in the surveys I was opening. The "scroll down" were the magic words that gave me the idea to test with a different survey. I will come back with the solution. Thanks @smburnett

**Comment by ifoche** [comment]
Apparently the problem came from a previous server configuration that is no longer the same. Some options that were previously uploaded to the server doesn't exist anymore, or changed their values, and the app was crashing whenever it found a non-existing option in the historical data. We've solved the issue by telling the app to ignore this situation and avoid trying to find that option.

**Comment by rodmelia** [comment]
@gtrsmith - Graham - this is a example of features that was not in the specs. And this is why we end up with unstable apps: every new feature rushed last minute means high risk of new bugs.
