### ISSUE TITLE
Results Module: Items with answers longer than Yes/No have numbered responses in the Review

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#56]
For questions with responses longer than "yes/no" the feedback screen just shows a number (i.e. 1, 2, 0). Is there anyway we could include what the response was? 
Also for the Stock items (i.e. respiratory timers, stethoscopes, otoscopes) regardless of the answer (0,1,2) all are considered a "fail"). How is the pass/fail set and can we fix it to match the questions? 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5754b59d2dfc6a0100e90264/41eaaaf9-1f63-4655-adaf-4101d5e865a4.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>10</td></tr><tr><td>Device type</td><td>SM-T230NU</td></tr><tr><td>Screen size</td><td>800</td></tr><tr><td>Screen size</td><td>800px by 1280px</td></tr><tr><td>Battery</td><td>21% Unplugged</td></tr><tr><td>Memory free</td><td>263 MB / 1319 MB</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=57553b36bf6039010022c19f&bnum=10)

**Comment by gtrsmith** [comment]
@smburnett I think this is a content issue and this should be fixed. Please take a look again and if persists we can take a look a the options. 

@ifoche  the feedback should always display the option name, rather than the code. Is this solvable in the app itself?

**Comment by smburnett** [comment]
I verified that this has been fixed. Thanks @gtrsmith!
