### ISSUE TITLE
Survey Selection: Alphabetical Order?

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#58]
Can we put the counties, sub-counties and health facilities in alphabetical order to make lookup easier? 
![screenshot_2016-06-07-10-25-19 1](https://cloud.githubusercontent.com/assets/18399454/15855287/4fc389f6-2cb7-11e6-9a15-6b3a355bba44.png)

**Comment by smburnett** [comment]
This has not been fixed. They are still out of alphabetical order
![screenshot_2016-06-23-04-05-45 1](https://cloud.githubusercontent.com/assets/18399454/16288749/3e97f2f4-38bd-11e6-8c71-715afd618832.png)

**Comment by ifoche** [comment]
@smburnett could you please send me by email the user/pass/server you're using to test? Just to check it and being sure of my answer. Thanks!
