### ISSUE TITLE
sburnett@path.org on build #10: Data sent but not showing up in shish also assessments not…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#59]
Feedback from sburnett@path.org : Data sent but not showing up in shish also assessments not done by this user are showing up - old ones from before training started 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5754b59d2dfc6a0100e90264/6b7d9e80-d03a-4560-a745-b4150dbb8209.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>10</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=575955b64d6deb01001b6eab&bnum=10)

**Comment by gtrsmith** [comment]
Hi Sarah, 

You just need to select 'this month' in the period section of event reports and this data will show up. You can also select 'last 12 months' and have them both selected at the same time. But this month's data will only show up if you also select 'this month'. 

Graham
