### ISSUE TITLE
sburnett@path.org on build #10: Screen keeps cutting off. We can usually fix it but clicking…

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/EDSApp#60]
Feedback from sburnett@path.org : Screen keeps cutting off. We can usually fix it but clicking on setting s then clicking off 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/56bbbce6cd51a40100d03a6e/5754b59d2dfc6a0100e90264/b25264d3-eef2-4774-a255-0190799de075.jpg" width="33%" height="33%" /><table><tr><td>Build</td><td>10</td></tr></table>

 [Link to buddybuild feedback from build 10](https://dashboard.buddybuild.com/apps/56bbbce6cd51a40100d03a6e/feedback?fid=57595952ccd6250100f9f82b&bnum=10)

**Comment by smburnett** [comment]
Same as #57
