### ISSUE TITLE
New Date Format Button: Additional line of dates on the left side of calendar

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#66]

**Comment by smburnett** [comment]
You can see in the screenshot below that there is an extra column of numbers on the left side of the calendar that are not relevant. 

![screenshot_2016-06-23-03-32-43 1](https://cloud.githubusercontent.com/assets/18399454/16288340/c2fc625a-38b8-11e6-8232-922aa62a57c5.png)

**Comment by rodmelia** [comment]
That's the week number. Ignacio will see if it is possible to remove that column number  - max research time 30min.
